name: vhs
on:
  push:
    paths: [ "*.tape", ".github/workflows/vhs.yaml" ]
    branches-ignore: [ "main" ]
    tags-ignore: [ "*" ]
jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: Build
        run: go build -o jirio .
      - uses: charmbracelet/vhs-action@v2
        with:
          path: 'demo.tape'
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "Update generated VHS GIF 📼"
          git push