name: vhs
on:
  push:
    paths: [ "*.tape", ".github/workflows/vhs.yaml" ]
    branches-ignore: [ "main" ]
    tags-ignore: [ "*" ]
jobs:
  vhs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'
      - name: Build
        run: go build -o jirio .
      - uses: charmbracelet/vhs-action@v2
        with:
          path: 'demo.tape'
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'